excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/
  - UrbanApplauseTest/
disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - identifier_name # need variable names to match json response from server (otherwise can't use default init from decoder implementation
force_try: warning
force_cast: warning
line_length:
  ignores_interpolated_strings: true
  ignores_comments: true
  ignores_urls: true
file_length:
  warning: 600
  error: 1000
type_name:
  allowed_symbols: ["_"]
type_body_length:
  - 400 # warning
  - 500 # error
function_body_length:
  - 90 # warning
  - 120 # error
large_tuple:
  - 3
  - 4
function_parameter_count:
  - 6
